### ISSUE TITLE
Cadastro de Turma

### ISSUE THREAD

**Issue by willgremio** [felipehertzer/gestaoescolar#15]
Cadastro de Turma

**Comment by felipehertzer** [comment]
Estou fazendo a associação das materias com a turma

**Comment by felipehertzer** [comment]
Estou fazendo a associação do professor com a materia

**Comment by felipehertzer** [comment]
Corrigi parte do erro, precisamos colocar o nome do professor quando estiver selecionado, só aparece quando nao está selecionado.

**Comment by luizar** [comment]
Arrumei o Create e Update. Tem que ver se precisa remover da lista os professores que já tem turma.
