### ISSUE TITLE
Bug editar pessoa

### ISSUE THREAD

**Issue by luizar** [felipehertzer/gestaoescolar#39]

**Comment by felipehertzer** [comment]
o que seria esse bug? a parte de excluir pessoa eu corrigi, também estava com problema

**Comment by luizar** [comment]
Na parte de editar. Tem que verificar se ao editar o tipo de pessoa permanesse o mesmo. Aí tem que dar o update, sem remover do banco. Pq quando o tipo é diferente tem que remover do banco e criar outro. É bem simples de arrumar, só não tive tempo.
